### PR TITLE
new config class - steadweb

### PR DESCRIPTION
**Pull request by PWesterdale**

### CODE REVIEW

**Comment by PWesterdale** [comment]
@steadweb I cannot be trusted to press the button :bomb:

**Comment by steadweb** [comment]
no you can't - that button is for grown ups only.

**Comment by PWesterdale** [comment]
Actualy consideration is that the key (shown as 8:45) would be the raw seconds of the day. This means for bookings I can blanket assign their business over the top from bookings for the required time. (currently set at 1 hour per booking)
So a booking on table 12 I can quickly assign table 12 to be busy across all the raw second values via multiplication.
This doesnt make much sense reading it back...

**Comment by PWesterdale** [comment]
A stretch goal for this would be to utilize Redis to store a cache for busy venues.
Something to think about...

**Comment by steadweb** [comment]
What about storing bookings only when they're booked? Then have a query to see if a booking exists for that time, if so, that isn't available. 

I reckon restaurants would be able to block book a specific time multiple times (i.e. 10, 8:45 bookings, each party of 2, meaning 10 tables of 2 required). 

```
bookings: [
    {
        time: "8:45",
        tables: [
            {id: "table1", seats: 2},
            {id: "table2", seats: 2}
        ],
        customer: id,
    }
]
```

**Comment by PWesterdale** [comment]
That's what I will be doing.
For now this is a bit early, this stage will basically draw up the map of tables / timeslots and realise there are no bookings so will blanket return 'all is well' on all timeslots.
This map is basically the data required to make a decision based on the current booking request.

**Comment by PWesterdale** [comment]
See:
https://github.com/reservat/vigilant-dollop/blob/master/model/Availability.js#L10

**Pull request merged**
